CREATE TABLE INSURANCE_POLICY(
PNUM    VARCHAR2(10),
NAME    VARCHAR2(25),
PREMIUM NUMBER(10,2),
TENTURE NUMBER(5),
ADDRESS VARCHAR2(50)
)

INSERT INTO INSURANCE_POLICY (PNUM, NAME, PREMIUM,TENTURE,ADDRESS) VALUES(?,?,?,?,?);

